### ISSUE TITLE
howto start it?

### ISSUE THREAD

**Issue by shorinji** [Andypro1/z1m1-tracker#1]
Sorry for posting an issue, but see no other clear way of communicating with this project.

How can I try running the tracker?
Don't see any basic setup instructions in the readme.
I have node v18.12.1 and have done `npm install` in both root and the src/server directory.
Running `npm run server` seems to start it up on localhost:8080 but the web page only responds with the text "Upgrade Required". 
A little help?

**Comment by Andypro1** [comment]
Hi @shorinji :

If you just want to use the tracker, you can use it at https://z1m1.andypro.net/ .

If you want to run it locally for development and/or solo play, run `npm run dev` from the project root directory.

This should start the app on `http://localhost:3000` .  Open `http://localhost:3000/solo` in your browser and the tracker should appear.

Configuring it for coop play in your local development environment is a little trickier.  You'll need to run both `npm run dev` and `npm run server` in separate terminals, but then also replace the endpoint on line 7 of `src\services\coop-client.js` to point to your local coop server instance.

Let me know if I can assist further.

**Comment by shorinji** [comment]
hi

Thanks mate!

/Fredrik
